from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameMain(object):
    def setupUi(self, FrameMain):
        FrameMain.setObjectName("FrameMain")
        FrameMain.setWindowModality(QtCore.Qt.NonModal)
        FrameMain.resize(900, 600)
        FrameMain.setMinimumSize(QtCore.QSize(900, 600))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrameMain.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(FrameMain)
        self.centralwidget.setObjectName("centralwidget")
        self.imageLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.imageLayout.setObjectName("imageLayout")
        self.imageWidget = QtWidgets.QWidget(self.centralwidget)
        self.imageWidget.setObjectName("imageWidget")
        self.imageLayout.addWidget(self.imageWidget)
        FrameMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FrameMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_analysis = QtWidgets.QMenu(self.menubar)
        self.menu_analysis.setObjectName("menu_analysis")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        FrameMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FrameMain)
        self.statusbar.setObjectName("statusbar")
        FrameMain.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(FrameMain)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(FrameMain)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(FrameMain)
        self.actionExit.setObjectName("actionExit")
        self.actionHeader = QtWidgets.QAction(FrameMain)
        self.actionHeader.setCheckable(False)
        self.actionHeader.setChecked(False)
        self.actionHeader.setEnabled(False)
        self.actionHeader.setObjectName("actionHeader")
        self.actionSpectrum = QtWidgets.QAction(FrameMain)
        self.actionSpectrum.setEnabled(False)
        self.actionSpectrum.setObjectName("actionSpectrum")
        self.actionAnalysis = QtWidgets.QAction(FrameMain)
        self.actionAnalysis.setEnabled(False)
        self.actionAnalysis.setObjectName("actionAnalysis")
        self.actionHelp = QtWidgets.QAction(FrameMain)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSpectrogram = QtWidgets.QAction(FrameMain)
        self.actionSpectrogram.setEnabled(False)
        self.actionSpectrogram.setObjectName("actionSpectrogram")
        self.menu_file.addAction(self.actionOpen)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionExit)
        self.menu_analysis.addAction(self.actionHeader)
        self.menu_analysis.addAction(self.actionSpectrogram)
        self.menu_analysis.addAction(self.actionSpectrum)
        self.menu_analysis.addSeparator()
        self.menu_analysis.addAction(self.actionAnalysis)
        self.menu_help.addAction(self.actionHelp)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_analysis.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(FrameMain)
        QtCore.QMetaObject.connectSlotsByName(FrameMain)

        return FrameMain

    def retranslateUi(self, FrameMain):
        _translate = QtCore.QCoreApplication.translate
        FrameMain.setWindowTitle(_translate("FrameMain", "Частотный анализатор"))
        self.menu_file.setTitle(_translate("FrameMain", "Файл"))
        self.menu_analysis.setTitle(_translate("FrameMain", "Анализ"))
        self.menu_help.setTitle(_translate("FrameMain", "Справка"))
        self.actionAbout.setText(_translate("FrameMain", "О программе..."))
        self.actionAbout.setStatusTip(_translate("FrameMain", "О программе"))
        self.actionOpen.setText(_translate("FrameMain", "Открыть файл"))
        self.actionOpen.setStatusTip(_translate("FrameMain", "Открыть файл"))
        self.actionOpen.setShortcut(_translate("FrameMain", "Ctrl+O"))
        self.actionExit.setText(_translate("FrameMain", "Выход"))
        self.actionExit.setStatusTip(_translate("FrameMain", "Выход из программы"))
        self.actionExit.setShortcut(_translate("FrameMain", "Ctrl+Q"))
        self.actionHeader.setText(_translate("FrameMain", "Данные из заголовка"))
        self.actionHeader.setStatusTip(_translate("FrameMain", "Данные из заголовка"))
        self.actionSpectrum.setText(_translate("FrameMain", "График спектра"))
        self.actionSpectrum.setStatusTip(_translate("FrameMain", "График спектра"))
        self.actionAnalysis.setText(_translate("FrameMain", "Начать анализ"))
        self.actionAnalysis.setStatusTip(_translate("FrameMain", "Анализ на наличие внесённых изменений"))
        self.actionHelp.setText(_translate("FrameMain", "Справка"))
        self.actionHelp.setShortcut(_translate("FrameMain", "F1"))
        self.actionSpectrogram.setText(_translate("FrameMain", "Спектрограмма"))
        self.actionSpectrogram.setStatusTip(_translate("FrameMain", "Спектрограмма"))

    def renameWindowTitle(self, FrameMain, path=""):
        if not path:
            title = "Частотный анализатор"
        else:
            title = "Частотный анализатор ({})".format(path)

        _translate = QtCore.QCoreApplication.translate
        FrameMain.setWindowTitle(_translate("FrameMain", title))
