from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameSpectrum(object):
    def setupUi(self, FrameSpectrum):
        FrameSpectrum.setObjectName("FrameSpectrum")
        FrameSpectrum.resize(800, 600)
        FrameSpectrum.setMinimumSize(QtCore.QSize(600, 600))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/icons/spectrum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrameSpectrum.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(FrameSpectrum)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageLayout = QtWidgets.QVBoxLayout()
        self.imageLayout.setObjectName("imageLayout")
        self.imageWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageWidget.sizePolicy().hasHeightForWidth())
        self.imageWidget.setSizePolicy(sizePolicy)
        self.imageWidget.setObjectName("imageWidget")
        self.imageLayout.addWidget(self.imageWidget)
        self.verticalLayout.addLayout(self.imageLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelScale = QtWidgets.QLabel(self.centralwidget)
        self.labelScale.setObjectName("labelScale")
        self.horizontalLayout.addWidget(self.labelScale)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.comboBoxScale = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxScale.setObjectName("comboBoxScale")
        self.comboBoxScale.addItem("")
        self.comboBoxScale.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxScale)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonOk = QtWidgets.QPushButton(self.centralwidget)
        self.buttonOk.setObjectName("buttonOk")
        self.horizontalLayout.addWidget(self.buttonOk)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 12)
        self.verticalLayout.setStretch(1, 1)
        FrameSpectrum.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrameSpectrum)
        QtCore.QMetaObject.connectSlotsByName(FrameSpectrum)

    def retranslateUi(self, FrameSpectrum):
        _translate = QtCore.QCoreApplication.translate
        FrameSpectrum.setWindowTitle(_translate("FrameSpectrum", "График спектра"))
        self.labelScale.setText(_translate("FrameSpectrum", "Шкала"))
        self.comboBoxScale.setItemText(0, _translate("FrameSpectrum", "Логарифмический"))
        self.comboBoxScale.setItemText(1, _translate("FrameSpectrum", "Линейный"))
        self.buttonOk.setText(_translate("FrameSpectrum", "OK"))
