from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameHeader(object):
    def setupUi(self, FrameHeader):
        FrameHeader.setObjectName("FrameHeader")
        FrameHeader.setWindowModality(QtCore.Qt.ApplicationModal)
        FrameHeader.resize(585, 525)
        FrameHeader.setMinimumSize(QtCore.QSize(585, 525))
        FrameHeader.setMaximumSize(QtCore.QSize(585, 525))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/header.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrameHeader.setWindowIcon(icon)

        self.tableInfo = QtWidgets.QTableWidget(FrameHeader)
        self.tableInfo.setGeometry(QtCore.QRect(80, 40, 431, 422))

        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableInfo.setFont(font)

        self.tableInfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableInfo.setAutoScroll(False)
        self.tableInfo.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableInfo.setCornerButtonEnabled(True)
        self.tableInfo.setObjectName("tableInfo")
        self.tableInfo.setColumnCount(1)
        self.tableInfo.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setItem(0, 0, item)
        self.tableInfo.horizontalHeader().setVisible(False)
        self.tableInfo.horizontalHeader().setDefaultSectionSize(204)
        self.buttonOk = QtWidgets.QPushButton(FrameHeader)
        self.buttonOk.setGeometry(QtCore.QRect(480, 480, 91, 31))
        self.buttonOk.setObjectName("buttonOk")

        self.retranslateUi(FrameHeader)
        QtCore.QMetaObject.connectSlotsByName(FrameHeader)

    def retranslateUi(self, FrameHeader):
        _translate = QtCore.QCoreApplication.translate
        FrameHeader.setWindowTitle(_translate("FrameHeader", "Информация об аудиофайле"))
        item = self.tableInfo.verticalHeaderItem(0)
        item.setText(_translate("FrameHeader", "Название трека"))
        item = self.tableInfo.verticalHeaderItem(1)
        item.setText(_translate("FrameHeader", "ChunkID"))
        item = self.tableInfo.verticalHeaderItem(2)
        item.setText(_translate("FrameHeader", "Размер Chunk ID(ChunkSize)"))
        item = self.tableInfo.verticalHeaderItem(3)
        item.setText(_translate("FrameHeader", "Format"))
        item = self.tableInfo.verticalHeaderItem(4)
        item.setText(_translate("FrameHeader", "Subchunk1ID"))
        item = self.tableInfo.verticalHeaderItem(5)
        item.setText(_translate("FrameHeader", "Размер SubChunk1ID (Subchunk1Size)"))
        item = self.tableInfo.verticalHeaderItem(6)
        item.setText(_translate("FrameHeader", "Аудиоформат"))
        item = self.tableInfo.verticalHeaderItem(7)
        item.setText(_translate("FrameHeader", "Количество каналов"))
        item = self.tableInfo.verticalHeaderItem(8)
        item.setText(_translate("FrameHeader", "Частота дискретизации"))
        item = self.tableInfo.verticalHeaderItem(9)
        item.setText(_translate("FrameHeader", "Байтрейт"))
        item = self.tableInfo.verticalHeaderItem(10)
        item.setText(_translate("FrameHeader", "Байт на сэмпл"))
        item = self.tableInfo.verticalHeaderItem(11)
        item.setText(_translate("FrameHeader", "Бит в сэмпле"))
        item = self.tableInfo.verticalHeaderItem(12)
        item.setText(_translate("FrameHeader", "Subchunk2ID"))
        item = self.tableInfo.verticalHeaderItem(13)
        item.setText(_translate("FrameHeader", "Размер SubChunk2ID (Subchunk2Size)"))
        item = self.tableInfo.horizontalHeaderItem(0)
        item.setText(_translate("FrameHeader", "Значение"))
        __sortingEnabled = self.tableInfo.isSortingEnabled()
        self.tableInfo.setSortingEnabled(False)
        self.tableInfo.setSortingEnabled(__sortingEnabled)
        self.buttonOk.setText(_translate("FrameHeader", "ОК"))
