from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameInfo(object):
    def setupUi(self, FrameInfo):
        FrameInfo.setObjectName("FrameInfo")
        FrameInfo.setWindowModality(QtCore.Qt.ApplicationModal)
        FrameInfo.resize(600, 570)
        FrameInfo.setMinimumSize(QtCore.QSize(600, 570))
        FrameInfo.setMaximumSize(QtCore.QSize(600, 570))

        self.tableInfo = QtWidgets.QTableWidget(FrameInfo)
        self.tableInfo.setGeometry(QtCore.QRect(80, 40, 431, 451))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableInfo.setFont(font)
        self.tableInfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableInfo.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableInfo.setCornerButtonEnabled(True)
        self.tableInfo.setObjectName("tableInfo")
        self.tableInfo.setColumnCount(1)
        self.tableInfo.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableInfo.setItem(0, 0, item)
        self.tableInfo.horizontalHeader().setVisible(False)
        self.tableInfo.horizontalHeader().setDefaultSectionSize(204)
        self.buttonOk = QtWidgets.QPushButton(FrameInfo)
        self.buttonOk.setGeometry(QtCore.QRect(480, 530, 91, 31))
        self.buttonOk.setObjectName("buttonOk")

        self.retranslateUi(FrameInfo)
        QtCore.QMetaObject.connectSlotsByName(FrameInfo)

    def retranslateUi(self, FrameInfo):
        _translate = QtCore.QCoreApplication.translate
        FrameInfo.setWindowTitle(_translate("FrameInfo", "Информация об аудиофайле"))
        item = self.tableInfo.verticalHeaderItem(0)
        item.setText(_translate("FrameInfo", "Название трека"))
        item = self.tableInfo.verticalHeaderItem(1)
        item.setText(_translate("FrameInfo", "Исходный размер"))
        item = self.tableInfo.verticalHeaderItem(2)
        item.setText(_translate("FrameInfo", "ChunkID"))
        item = self.tableInfo.verticalHeaderItem(3)
        item.setText(_translate("FrameInfo", "Размер Chunk ID(ChunkSize)"))
        item = self.tableInfo.verticalHeaderItem(4)
        item.setText(_translate("FrameInfo", "Format"))
        item = self.tableInfo.verticalHeaderItem(5)
        item.setText(_translate("FrameInfo", "Subchunk1ID"))
        item = self.tableInfo.verticalHeaderItem(6)
        item.setText(_translate("FrameInfo", "Размер SubChunk1ID (Subchunk1Size)"))
        item = self.tableInfo.verticalHeaderItem(7)
        item.setText(_translate("FrameInfo", "Аудиоформат"))
        item = self.tableInfo.verticalHeaderItem(8)
        item.setText(_translate("FrameInfo", "Количество каналов"))
        item = self.tableInfo.verticalHeaderItem(9)
        item.setText(_translate("FrameInfo", "Частота дискретизации"))
        item = self.tableInfo.verticalHeaderItem(10)
        item.setText(_translate("FrameInfo", "Байтрейт"))
        item = self.tableInfo.verticalHeaderItem(11)
        item.setText(_translate("FrameInfo", "Байт на сэмпл"))
        item = self.tableInfo.verticalHeaderItem(12)
        item.setText(_translate("FrameInfo", "Бит в сэмпле"))
        item = self.tableInfo.verticalHeaderItem(13)
        item.setText(_translate("FrameInfo", "Subchunk2ID"))
        item = self.tableInfo.verticalHeaderItem(14)
        item.setText(_translate("FrameInfo", "Размер SubChunk2ID (Subchunk2Size)"))
        item = self.tableInfo.horizontalHeaderItem(0)
        item.setText(_translate("FrameInfo", "Значение"))
        __sortingEnabled = self.tableInfo.isSortingEnabled()
        self.tableInfo.setSortingEnabled(False)
        self.tableInfo.setSortingEnabled(__sortingEnabled)
        self.buttonOk.setText(_translate("FrameInfo", "ОК"))
